caycanh/caycanh/Models/NhanVien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caycanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.DonDatHang = new HashSet<DonDatHang>();
        }
    
        public string MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public string ChucVu { get; set; }
        public Nullable<decimal> Luong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHang> DonDatHang { get; set; }
    }
}

caycanh/caycanh/Controllers/NhanVienController.cs
using caycanh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace caycanh.Controllers
{
    public class NhanVienController : Controller
    {
        // GET: NhanVien
        public ActionResult Index()
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            List<NhanVien> nhanViens = db.NhanVien.ToList();
            return View(nhanViens);
        }
        public ActionResult Create()
        {
            return View();
        }

        // POST: LoaiCay/Create
        [HttpPost]
        public ActionResult Create(NhanVien nv)
        {
            if (ModelState.IsValid)
            {
                QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
                db.NhanVien.Add(nv);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nv);
        }
        // GET: LoaiCay/Details/{id}
        public ActionResult Details(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            NhanVien nhanVien = db.NhanVien.FirstOrDefault(l => l.MaNhanVien == id);

            if (nhanVien == null)
            {
                return HttpNotFound();
            }

            return View(nhanVien);
        }
        // GET: LoaiCay/Edit/{id}
        public ActionResult Edit(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            NhanVien nhanVien = db.NhanVien.FirstOrDefault(l => l.MaNhanVien == id);

            if (nhanVien == null)
            {
                return HttpNotFound();
            }

            return View(nhanVien);
        }

        // POST: LoaiCay/Edit/{id}
        [HttpPost]
        public ActionResult Edit(String id, NhanVien editednv)
        {
            if (ModelState.IsValid)
            {
                QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
                NhanVien nhanVien = db.NhanVien.FirstOrDefault(l => l.MaNhanVien == id);

                if (nhanVien == null)
                {
                    return HttpNotFound();
                }
                nhanVien.MaNhanVien = editednv.MaNhanVien;
                nhanVien.TenNhanVien = editednv.TenNhanVien;
                nhanVien.ChucVu=editednv.ChucVu;
                nhanVien.Luong=editednv.Luong;  

                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(editednv);
        }
        // GET: LoaiCay/Delete/{id}
        public ActionResult Delete(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            NhanVien nhanVien = db.NhanVien.FirstOrDefault(l => l.MaNhanVien == id);

            if (nhanVien == null)
            {
                return HttpNotFound();
            }

            return View(nhanVien);
        }

        // POST: LoaiCay/Delete/{id}
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            NhanVien nhanVien = db.NhanVien.FirstOrDefault(l => l.MaNhanVien == id);

            if (nhanVien == null)
            {
                return HttpNotFound();
            }

            db.NhanVien.Remove(nhanVien);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

caycanh/caycanh/Views/NhanVien/Create.cshtml
@model caycanh.Models.NhanVien
@{
    ViewBag.Title = "Thêm Nhân Viên";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
<h2>Tạo mới Nhân Viên</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.MaNhanVien, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.MaNhanVien, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.MaNhanVien, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenNhanVien, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.TenNhanVien, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.TenNhanVien, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ChucVu, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.ChucVu, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ChucVu, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Luong, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.Luong, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Luong, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <input type="submit" value="Tạo mới" class="btn btn-primary custom-button" />
        @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-default" })
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

caycanh/caycanh/Views/NhanVien/Delete.cshtml
@model caycanh.Models.NhanVien

@{
    ViewBag.Title = "Delete";
}

<h3>Bạn có chắc chắn muốn xóa bản ghi này?</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaNhanVien)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaNhanVien)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TenNhanVien)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TenNhanVien)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ChucVu)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ChucVu)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Luong)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Luong)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

caycanh/caycanh/Views/NhanVien/Details.cshtml
@model caycanh.Models.NhanVien
@{
    ViewBag.Title = "Xem Chi Tiết";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Chi tiết Nhan Viên</h2>

<table class="table">
    <tr>
        <th>Mã Nhân Viên:</th>
        <td>@Model.MaNhanVien</td>
    </tr>
    <tr>
        <th>Tên Nhân Viên:</th>
        <td>@Model.TenNhanVien</td>
    </tr>
    <tr>
        <th>Chức Vụ:</th>
        <td>@Model.ChucVu</td>
    </tr>
    <tr>
        <th>Lương:</th>
        <td>@Model.Luong</td>
    </tr>
</table>

<p>
    @Html.ActionLink("Quay lại", "Index")
</p>

caycanh/caycanh/Views/NhanVien/Edit.cshtml
@model caycanh.Models.NhanVien

<h2>Chỉnh sửa chi tiết</h2>

@using (Html.BeginForm("Edit", "NhanVien", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(model => model.MaNhanVien, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.MaNhanVien, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.MaNhanVien, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenNhanVien, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.TenNhanVien, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.TenNhanVien, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ChucVu, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.ChucVu, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ChucVu, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Luong, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.Luong, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Luong, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
    </div>
}

caycanh/caycanh/Views/NhanVien/Index.cshtml
@model List<caycanh.Models.NhanVien>
@{
    ViewBag.Title = "Nhân Viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Danh sách Nhân Viên</h2>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />


<p>
    <a href="@Url.Action("Create")" class="btn btn-primary">
        <i class="fas fa-plus"></i> Thêm mới
    </a>
</p>

<table class="table">
    <tr>
        <th>Mã Nhân Viên</th>
        <th>Tên Nhân Viên</th>
        <th>Chức Vụ</th>
        <th>Lương</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.MaNhanVien</td>
            <td>@item.TenNhanVien</td>
            <td>@item.ChucVu</td>
            <td>@item.Luong</td>
            <td>
                <a href="@Url.Action("Details", new { id = item.MaNhanVien })" class="btn btn-info btn-sm">
                    <i class="fas fa-eye"></i> Chi tiết
                </a>
                <a href="@Url.Action("Edit", new { id = item.MaNhanVien })" class="btn btn-warning btn-sm">
                    <i class="fas fa-edit"></i> Sửa
                </a>
                <a href="@Url.Action("Delete", new { id = item.MaNhanVien })" class="btn btn-danger btn-sm">
                    <i class="fas fa-trash-alt"></i> Xóa
                </a>
            </td>
        </tr>
    }
</table>