caycanh/caycanh/Controllers/ChiTietDonHangController.cs
using caycanh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace caycanh.Controllers
{
    public class ChiTietDonHangController : Controller
    {
        private QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
        // GET: ChiTietDonHang
        public ActionResult Index()
        {
            List<ChiTietDonDatHang> chiTiets = db.ChiTietDonDatHang.ToList();
            return View(chiTiets);
        }
        public ActionResult Create()
        {
            List<SanPham> sanPhamList = db.SanPham.ToList();
            ViewBag.SanPhamList = sanPhamList;
            List<CayCanh> cayCanhList = db.CayCanh.ToList();
            ViewBag.CayCanhList = cayCanhList;
            List<DonDatHang> donHangList = db.DonDatHang.ToList();
            ViewBag.DonHangList = donHangList;
            return View();
        }

        // POST: CayCanh/Create
        [HttpPost]
        public ActionResult Create(ChiTietDonDatHang chitiet)
        {
            if (ModelState.IsValid)
            {
                db.ChiTietDonDatHang.Add(chitiet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            List<SanPham> sanPhamList = db.SanPham.ToList();
            ViewBag.SanPhamList = sanPhamList;
            List<CayCanh> cayCanhList = db.CayCanh.ToList();
            ViewBag.CayCanhList = cayCanhList;
            List<DonDatHang> donHangList = db.DonDatHang.ToList();
            ViewBag.DonHangList = donHangList;

            return View(chitiet);
        }

        public ActionResult Edit(string id)
        {

            ChiTietDonDatHang chitiet = db.ChiTietDonDatHang.FirstOrDefault(l => l.MaDonDatHang == id);
            if (chitiet == null)
            {
                return HttpNotFound();
            }

            List<SanPham> sanPhamList = db.SanPham.ToList();
            ViewBag.SanPhamList = sanPhamList;
            List<CayCanh> cayCanhList = db.CayCanh.ToList();
            ViewBag.CayCanhList = cayCanhList;
            List<DonDatHang> donHangList = db.DonDatHang.ToList();
            ViewBag.DonHangList = donHangList;

            return View(chitiet);
        }

        // POST: DonHang/Edit/{id}
        [HttpPost]
        public ActionResult Edit(string id, ChiTietDonDatHang editchiTiet)
        {
            if (ModelState.IsValid)
            {
                DonDatHang donHang = db.DonDatHang.FirstOrDefault(d => d.MaDonDatHang == editchiTiet.MaDonDatHang);
                if (donHang == null)
                {
                    return HttpNotFound();
                }

                ChiTietDonDatHang chitiet = db.ChiTietDonDatHang.FirstOrDefault(l => l.MaDonDatHang == id);
                if (chitiet == null)
                {
                    return HttpNotFound();
                }

                // Update the properties of the ChiTietDonDatHang object
                chitiet.MaDonDatHang = editchiTiet.MaDonDatHang;
                chitiet.MaCay = editchiTiet.MaCay;
                chitiet.MaSanPham = editchiTiet.MaSanPham;
                chitiet.SoLuong = editchiTiet.SoLuong;
                chitiet.GiamGia = editchiTiet.GiamGia;
                chitiet.ChietKhau = editchiTiet.ChietKhau;
                chitiet.GiaTien = editchiTiet.GiaTien;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            List<SanPham> sanPhamList = db.SanPham.ToList();
            ViewBag.SanPhamList = sanPhamList;
            List<CayCanh> cayCanhList = db.CayCanh.ToList();
            ViewBag.CayCanhList = cayCanhList;
            List<DonDatHang> donHangList = db.DonDatHang.ToList();
            ViewBag.DonHangList = donHangList;

            return View(editchiTiet);
        }

        public ActionResult Delete(string id)
        {
            ChiTietDonDatHang chitiet = db.ChiTietDonDatHang.FirstOrDefault(l => l.MaDonDatHang == id);
            if (chitiet == null)
            {
                return HttpNotFound();
            }

            return View(chitiet);
        }

        // POST: DonHang/Delete/{id}
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {
            ChiTietDonDatHang chitiet = db.ChiTietDonDatHang.FirstOrDefault(l => l.MaDonDatHang == id);
            if (chitiet == null)
            {
                return HttpNotFound();
            }

            db.ChiTietDonDatHang.Remove(chitiet);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

caycanh/caycanh/Views/ChiTietDonHang/Create.cshtml
@model caycanh.Models.ChiTietDonDatHang
@using caycanh.Models
@{
    ViewBag.Title = "Thêm Sản Phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thêm Mới Chi Tiết Đơn Hàng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.MaDonDatHang, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.MaDonDatHang, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.MaDonDatHang, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaCay, htmlAttributes: new { @class = "control-label" })
        @Html.DropDownListFor(model => model.MaCay, new SelectList((List<CayCanh>)ViewBag.CayCanhList, "MaCay", "TenCay"), "Chọn cây", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.MaCay, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaSanPham, htmlAttributes: new { @class = "control-label" })
        @Html.DropDownListFor(model => model.MaSanPham, new SelectList((List<SanPham>)ViewBag.SanPhamList, "MaSanPham", "TenSanPham"), "Chọn sản phẩm", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.MaSanPham, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ChietKhau, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.ChietKhau, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ChietKhau, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiamGia, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.GiamGia, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.GiamGia, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.GiaTien, htmlAttributes: new { @class = "control-label" })
        @Html.TextBoxFor(model => model.GiaTien, new { @class = "form-control datepicker" })
        @Html.ValidationMessageFor(model => model.GiaTien)
    </div>

    <div class="form-group">
        <input type="submit" value="Tạo mới" class="btn btn-primary custom-button" />
        @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-default" })
    </div>
}

caycanh/caycanh/Views/ChiTietDonHang/Delete.cshtml
@model caycanh.Models.ChiTietDonDatHang

<h3>Bạn có chắc chắn muốn xóa bản ghi này?</h3>
<div>
    <h4>MaDonDatHang: @Model.MaDonDatHang</h4>
    <h4>MaCay: @Model.MaCay</h4>
    <h4>MaSanPham: @Model.MaSanPham</h4>
    <h4>SoLuong: @Model.SoLuong</h4>
    <h4>GiamGia: @Model.GiamGia</h4>
    <h4>ChietKhau: @Model.ChietKhau</h4>
    <h4>GiaTien: @Model.GiaTien</h4>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}

caycanh/caycanh/Views/ChiTietDonHang/Edit.cshtml
@model caycanh.Models.ChiTietDonDatHang
@using caycanh.Models

<h2>Chỉnh sửa chi tiết</h2>

@using (Html.BeginForm("Edit", "ChiTietDonHang", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.MaDonDatHang, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.MaDonDatHang, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.MaDonDatHang, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaCay, htmlAttributes: new { @class = "control-label" })
        @Html.DropDownListFor(model => model.MaCay, new SelectList((List<CayCanh>)ViewBag.CayCanhList, "MaCay", "TenCay"), "Chọn cây", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.MaCay, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaSanPham, htmlAttributes: new { @class = "control-label" })
        @Html.DropDownListFor(model => model.MaSanPham, new SelectList((List<SanPham>)ViewBag.SanPhamList, "MaSanPham", "TenSanPham"), "Chọn sản phẩm", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.MaSanPham, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ChietKhau, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.ChietKhau, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ChietKhau, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiamGia, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.GiamGia, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.GiamGia, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.GiaTien, htmlAttributes: new { @class = "control-label" })
        @Html.TextBoxFor(model => model.GiaTien, new { @class = "form-control datepicker" })
        @Html.ValidationMessageFor(model => model.GiaTien)
    </div>

    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
    </div>
}

caycanh/caycanh/Views/ChiTietDonHang/Index.cshtml
@model List<caycanh.Models.ChiTietDonDatHang>
@{
    ViewBag.Title = "Đơn Hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Danh sách Đơn Đặt Hàng</h2>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

<p>
    <a href="@Url.Action("Create")" class="btn btn-primary">
        <i class="fas fa-plus"></i> Thêm mới
    </a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>Mã Sản Phẩm</th>
            <th>Mã Cây</th>
            <th>Số Lượng</th>
            <th>Giảm Giá</th>
            <th>Chiết Khấu</th>
            <th>Giá tiền</th>
            <th>Thao tác</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var chiTiet in Model)
        {
            <tr>
                <td>@chiTiet.MaSanPham</td>
                <td>@chiTiet.MaCay</td>
                <td>@chiTiet.SoLuong</td>
                <td>@chiTiet.GiamGia</td>
                <td>@chiTiet.ChietKhau</td>
                <td>@chiTiet.GiaTien</td>
                <td>
                    <a href="@Url.Action("Edit", new { id = chiTiet.MaDonDatHang })" class="btn btn-warning btn-sm">
                        <i class="fas fa-edit"></i> Sửa
                    </a>
                    <a href="@Url.Action("Delete", new { id = chiTiet.MaDonDatHang })" class="btn btn-danger btn-sm">
                        <i class="fas fa-trash-alt"></i> Xóa
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<style>
    .btn-primary {
        background-color: #007bff; /* Replace with your desired color */
        border-color: #007bff; /* Replace with your desired color */
    }

    .btn-warning {
        background-color: #ffc107; /* Replace with your desired color */
        border-color: #ffc107; /* Replace with your desired color */
    }

    .btn-danger {
        background-color: #dc3545; /* Replace with your desired color */
        border-color: #dc3545; /* Replace with your desired color */
    }
</style>