caycanh/caycanh/Models/KhachHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caycanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DonDatHang = new HashSet<DonDatHang>();
        }
    
        public string MaKhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHang> DonDatHang { get; set; }
    }
}

caycanh/caycanh/Controllers/KhachHangController.cs
using caycanh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace caycanh.Controllers
{
    public class KhachHangController : Controller
    {
        // GET: KhachHang
        public ActionResult Index()
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            List<KhachHang> khachHangs = db.KhachHang.ToList();
            return View(khachHangs);
        }
        public ActionResult Create()
        {
            return View();
        }

        // POST: LoaiCay/Create
        [HttpPost]
        public ActionResult Create(KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
                db.KhachHang.Add(khachHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(khachHang);
        }
        public ActionResult Details(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            KhachHang khachHang = db.KhachHang.FirstOrDefault(l => l.MaKhachHang == id);

            if (khachHang == null)
            {
                return HttpNotFound();
            }

            return View(khachHang);
        }
        public ActionResult Edit(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            KhachHang khachHang = db.KhachHang.FirstOrDefault(l => l.MaKhachHang == id);

            if (khachHang == null)
            {
                return HttpNotFound();
            }

            return View(khachHang);
        }

        // POST: LoaiCay/Edit/{id}
        [HttpPost]
        public ActionResult Edit(String id, KhachHang editedKhachHang)
        {
            if (ModelState.IsValid)
            {
                QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
                KhachHang khachHang = db.KhachHang.FirstOrDefault(l => l.MaKhachHang == id);

                if (khachHang == null)
                {
                    return HttpNotFound();
                }
                khachHang.MaKhachHang = editedKhachHang.MaKhachHang;
                khachHang.TenKhachHang = editedKhachHang.TenKhachHang;
                khachHang.DiaChi = editedKhachHang.DiaChi;
                khachHang.SoDienThoai = editedKhachHang.SoDienThoai;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(editedKhachHang);
        }
        public ActionResult Delete(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            KhachHang khachHang = db.KhachHang.FirstOrDefault(l => l.MaKhachHang == id);

            if (khachHang == null)
            {
                return HttpNotFound();
            }

            return View(khachHang);
        }

        // POST: LoaiCay/Delete/{id}
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            KhachHang khachHang = db.KhachHang.FirstOrDefault(l => l.MaKhachHang == id);

            if (khachHang == null)
            {
                return HttpNotFound();
            }

            db.KhachHang.Remove(khachHang);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

caycanh/caycanh/Views/KhachHang/Create.cshtml
@model caycanh.Models.KhachHang
@{
    ViewBag.Title = "Thêm Khách Hàng";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
<h2>Tạo Mới Khách Hàng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.MaKhachHang, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.MaKhachHang, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.MaKhachHang, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenKhachHang, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.TenKhachHang, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.TenKhachHang, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoDienThoai, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <input type="submit" value="Tạo mới" class="btn btn-primary custom-button" />
        @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-default" })
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

caycanh/caycanh/Views/KhachHang/Delete.cshtml
@model caycanh.Models.KhachHang

@{
    ViewBag.Title = "Delete";
}


<h3>Bạn có chắc chắn muốn xóa bản ghi này?</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaKhachHang)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaKhachHang)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TenKhachHang)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TenKhachHang)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SoDienThoai)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SoDienThoai)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

caycanh/caycanh/Views/KhachHang/Details.cshtml
@model caycanh.Models.KhachHang
@{
    ViewBag.Title = "Xem Chi Tiết";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Chi tiết Loại cây</h2>

<table class="table">
    <tr>
        <th>Mã khách Hàng:</th>
        <td>@Model.MaKhachHang</td>
    </tr>
    <tr>
        <th>Tên Khách Hàng:</th>
        <td>@Model.TenKhachHang</td>
    </tr>
    <tr>
        <th>Địa Chỉ:</th>
        <td>@Model.DiaChi</td>
    </tr>
    <tr>
        <th>Số Điện Thoại:</th>
        <td>@Model.TenKhachHang</td>
    </tr>
</table>

<p>
    @Html.ActionLink("Quay lại", "Index")
</p>

caycanh/caycanh/Views/KhachHang/Edit.cshtml
@model caycanh.Models.KhachHang

<h2>Chỉnh sửa chi tiết</h2>

@using (Html.BeginForm("Edit", "KhachHang", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(model => model.MaKhachHang, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.MaKhachHang, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.MaKhachHang, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenKhachHang, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.TenKhachHang, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.TenKhachHang, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoDienThoai, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
    </div>
}

caycanh/caycanh/Views/KhachHang/Index.cshtml
@model List<caycanh.Models.KhachHang>
@{
    ViewBag.Title = "Khách Hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Danh Sách Khách Hàng</h2>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />


<p>
    <a href="@Url.Action("Create")" class="btn btn-primary">
        <i class="fas fa-plus"></i> Thêm mới
    </a>
</p>

<table class="table">
    <tr>
        <th>Mã Khách Hàng</th>
        <th>Tên Khách Hàng</th>
        <th>Địa Chỉ</th>
        <th>Số Điện Thoại</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.MaKhachHang</td>
            <td>@item.TenKhachHang</td>
            <td>@item.DiaChi</td>
            <td>@item.SoDienThoai</td>
            <td>
                <a href="@Url.Action("Details", new { id = item.MaKhachHang })" class="btn btn-info btn-sm">
                    <i class="fas fa-eye"></i> Chi tiết
                </a>
                <a href="@Url.Action("Edit", new { id = item.MaKhachHang })" class="btn btn-warning btn-sm">
                    <i class="fas fa-edit"></i> Sửa
                </a>
                <a href="@Url.Action("Delete", new { id = item.MaKhachHang })" class="btn btn-danger btn-sm">
                    <i class="fas fa-trash-alt"></i> Xóa
                </a>
            </td>
        </tr>
    }
</table>