caycanh/caycanh/Controllers/CayCanhController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using caycanh.Models;

namespace caycanh.Controllers
{
    public class CayCanhController : Controller
    {
        private QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();

        // GET: CayCanh
        public ActionResult Index()
        {
            List<CayCanh> cayCanhs = db.CayCanh.ToList();
            return View(cayCanhs);
        }
        public ActionResult cay()
        {
            List<CayCanh> cayCanhs = db.CayCanh.ToList();
            return View(cayCanhs);
        }

        // GET: CayCanh/Create
        public ActionResult Create()
        {
            List<LoaiCay> loaiCayList = db.LoaiCay.ToList();
            ViewBag.LoaiCayList = loaiCayList;

            return View();
        }

        // POST: CayCanh/Create
        [HttpPost]
        public ActionResult Create(CayCanh cayCanh)
        {
            if (ModelState.IsValid)
            {
                db.CayCanh.Add(cayCanh);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            List<LoaiCay> loaiCayList = db.LoaiCay.ToList();
            ViewBag.LoaiCayList = loaiCayList;

            return View(cayCanh);
        }

        public ActionResult Details(string id)
        {
            CayCanh cayCanh = db.CayCanh.FirstOrDefault(l => l.MaCay == id);

            if (cayCanh == null)
            {
                return HttpNotFound();
            }

            return View(cayCanh);
          
        }
        public ActionResult chitiet(string id)
        {
            CayCanh cayCanh = db.CayCanh.FirstOrDefault(l => l.MaCay == id);

            if (cayCanh == null)
            {
                return HttpNotFound();
            }

            return View(cayCanh);

        }

        public ActionResult Edit(string id)
        {
            CayCanh cayCanh = db.CayCanh.FirstOrDefault(l => l.MaCay == id);

            if (cayCanh == null)
            {
                return HttpNotFound();
            }

            List<LoaiCay> loaiCayList = db.LoaiCay.ToList();
            ViewBag.LoaiCayList = loaiCayList;

            return View(cayCanh);
        }

        // POST: CayCanh/Edit/{id}
        [HttpPost]
        public ActionResult Edit(string id, CayCanh editedCayCanh)
        {
            if (ModelState.IsValid)
            {
                CayCanh cayCanh = db.CayCanh.FirstOrDefault(l => l.MaCay == id);

                if (cayCanh == null)
                {
                    return HttpNotFound();
                }

                cayCanh.MaCay = editedCayCanh.MaCay;
                cayCanh.TenCay = editedCayCanh.TenCay;
                cayCanh.GiaTien = editedCayCanh.GiaTien;
                cayCanh.MaLoaiCay = editedCayCanh.MaLoaiCay;
                cayCanh.NgayTrong = editedCayCanh.NgayTrong;
                cayCanh.SoLuong = editedCayCanh.SoLuong;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(editedCayCanh);
        }
        public ActionResult Delete(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            CayCanh cayCanh = db.CayCanh.FirstOrDefault(l => l.MaCay == id);
            if (cayCanh == null)
            {
                return HttpNotFound();
            }

            return View(cayCanh);
        }

        // POST: LoaiCay/Delete/{id}
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            CayCanh cayCanh = db.CayCanh.FirstOrDefault(l => l.MaCay == id);

            if (cayCanh == null)
            {
                return HttpNotFound();
            }

            db.CayCanh.Remove(cayCanh);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

caycanh/caycanh/Controllers/DonHangController.cs
using caycanh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace caycanh.Controllers
{
    public class DonHangController : Controller
    {
        private QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();

        // GET: DonHang
        public ActionResult Index()
        {
            List<DonDatHang> donDatHangs = db.DonDatHang.ToList();
            return View(donDatHangs);
        }

        public ActionResult Create()
        {
            List<KhachHang> khachHangList = db.KhachHang.ToList();
            ViewBag.KhachHangList = khachHangList;
            List<NhanVien> nhanVienList = db.NhanVien.ToList();
            ViewBag.NhanVienList = nhanVienList;
            return View();
        }

        // POST: DonHang/Create
        [HttpPost]
        public ActionResult Create(DonDatHang donDatHang)
        {
            if (ModelState.IsValid)
            {
                db.DonDatHang.Add(donDatHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            List<KhachHang> khachHangList = db.KhachHang.ToList();
            ViewBag.KhachHangList = khachHangList;
            List<NhanVien> nhanVienList = db.NhanVien.ToList();
            ViewBag.NhanVienList = nhanVienList;

            return View(donDatHang);
        }

        // GET: DonHang/Details/{id}
        public ActionResult Details(string id)
        {
            DonDatHang donDatHang = db.DonDatHang.Find(id);
            if (donDatHang == null)
            {
                return HttpNotFound();
            }

            List<ChiTietDonDatHang> chiTietDonDatHangs = db.ChiTietDonDatHang.Where(c => c.MaDonDatHang == id).ToList();
            donDatHang.ChiTietDonDatHang = chiTietDonDatHangs;

            ViewBag.CayCanhList = db.CayCanh.ToList(); 
            ViewBag.SanPhamList=db.SanPham.ToList();

            return View(donDatHang);
        }

        public ActionResult Edit(string id)
        {
            DonDatHang donDatHang = db.DonDatHang.FirstOrDefault(l => l.MaDonDatHang == id);
            if (donDatHang == null)
            {
                return HttpNotFound();
            }

            List<KhachHang> khachHangList = db.KhachHang.ToList();
            ViewBag.KhachHangList = khachHangList;
            List<NhanVien> nhanVienList = db.NhanVien.ToList();
            ViewBag.NhanVienList = nhanVienList;

            return View(donDatHang);
        }

        // POST: DonHang/Edit/{id}
        [HttpPost]
        public ActionResult Edit(string id, DonDatHang editedDonDatHang)
        {
            if (ModelState.IsValid)
            {
                DonDatHang donDatHang = db.DonDatHang.Find(id);
                if (donDatHang == null)
                {
                    return HttpNotFound();
                }

                // Update the properties of the DonDatHang object
                donDatHang.MaKhachHang = editedDonDatHang.MaKhachHang;
                donDatHang.MaNhanVien = editedDonDatHang.MaNhanVien;
                donDatHang.NgayDatHang = editedDonDatHang.NgayDatHang;
                donDatHang.GiaTien=editedDonDatHang.GiaTien;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            List<KhachHang> khachHangList = db.KhachHang.ToList();
            ViewBag.KhachHangList = khachHangList;
            List<NhanVien> nhanVienList = db.NhanVien.ToList();
            ViewBag.NhanVienList = nhanVienList;

            return View(editedDonDatHang);
        }

        public ActionResult Delete(string id)
        {
            DonDatHang donDatHang = db.DonDatHang.Find(id);
            if (donDatHang == null)
            {
                return HttpNotFound();
            }

            return View(donDatHang);
        }

        // POST: DonHang/Delete/{id}
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {
            DonDatHang donDatHang = db.DonDatHang.Find(id);
            if (donDatHang == null)
            {
                return HttpNotFound();
            }

            db.DonDatHang.Remove(donDatHang);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        
    }
}

caycanh/caycanh/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace caycanh.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Admin()
        {
            return View();
        }
    }
}

caycanh/caycanh/Controllers/LoaiCayController.cs
using caycanh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace caycanh.Controllers
{
    public class LoaiCayController : Controller
    {
        // GET: LoaiCay
        public ActionResult Index()
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            List<LoaiCay> loaiCays = db.LoaiCay.ToList();
            return View(loaiCays);
        }

        // GET: LoaiCay/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LoaiCay/Create
        [HttpPost]
        public ActionResult Create(LoaiCay loaiCay)
        {
            if (ModelState.IsValid)
            {
                QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
                db.LoaiCay.Add(loaiCay);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(loaiCay);
        }
        // GET: LoaiCay/Details/{id}
        public ActionResult Details(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            LoaiCay loaiCay = db.LoaiCay.FirstOrDefault(l => l.MaLoaiCay == id);

            if (loaiCay == null)
            {
                return HttpNotFound();
            }

            return View(loaiCay);
        }
        // GET: LoaiCay/Edit/{id}
        public ActionResult Edit(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            LoaiCay loaiCay = db.LoaiCay.FirstOrDefault(l => l.MaLoaiCay == id);

            if (loaiCay == null)
            {
                return HttpNotFound();
            }

            return View(loaiCay);
        }

        // POST: LoaiCay/Edit/{id}
        [HttpPost]
        public ActionResult Edit(String id, LoaiCay editedLoaiCay)
        {
            if (ModelState.IsValid)
            {
                QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
                LoaiCay loaiCay = db.LoaiCay.FirstOrDefault(l => l.MaLoaiCay == id);

                if (loaiCay == null)
                {
                    return HttpNotFound();
                }
                loaiCay.MaLoaiCay = editedLoaiCay.MaLoaiCay;
                loaiCay.TenLoaiCay = editedLoaiCay.TenLoaiCay;

                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(editedLoaiCay);
        }
        // GET: LoaiCay/Delete/{id}
        public ActionResult Delete(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            LoaiCay loaiCay = db.LoaiCay.FirstOrDefault(l => l.MaLoaiCay == id);

            if (loaiCay == null)
            {
                return HttpNotFound();
            }

            return View(loaiCay);
        }

        // POST: LoaiCay/Delete/{id}
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            LoaiCay loaiCay = db.LoaiCay.FirstOrDefault(l => l.MaLoaiCay == id);

            if (loaiCay == null)
            {
                return HttpNotFound();
            }

            db.LoaiCay.Remove(loaiCay);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

caycanh/caycanh/Controllers/SanPhamController.cs
using caycanh.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace caycanh.Controllers
{
    public class SanPhamController : Controller
    {
        private QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
        // GET: SanPham
        public ActionResult Index()
        {
            List<SanPham> sanPhams = db.SanPham.ToList();
            return View(sanPhams);
        }
        public ActionResult sanpham()
        {
            List<SanPham> sanPhams = db.SanPham.ToList();
            return View(sanPhams);
        }
        public ActionResult Create()
        {
            List<NhaCungCap> nhaCungCapList = db.NhaCungCap.ToList();
            ViewBag.NhaCungCapList = nhaCungCapList;

            return View();
        }

        // POST: CayCanh/Create
        [HttpPost]
        public ActionResult Create(SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.SanPham.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            List<NhaCungCap> nhaCungCapList = db.NhaCungCap.ToList();
            ViewBag.NhaCungCapList = nhaCungCapList;

            return View(sanPham);
        }
        public ActionResult Details(string id)
        {
            SanPham sanPham = db.SanPham.FirstOrDefault(l => l.MaSanPham == id);

            if (sanPham == null)
            {
                return HttpNotFound();
            }

            return View(sanPham);

        }
        public ActionResult chitiet(string id)
        {
            SanPham sanPham = db.SanPham.FirstOrDefault(l => l.MaSanPham == id);

            if (sanPham == null)
            {
                return HttpNotFound();
            }

            return View(sanPham);

        }
        public ActionResult Edit(string id)
        {
            SanPham sanPham = db.SanPham.FirstOrDefault(l => l.MaSanPham == id);

            if (sanPham == null)
            {
                return HttpNotFound();
            }

            List<NhaCungCap> nhaCungCapList = db.NhaCungCap.ToList();
            ViewBag.NhaCungCapList = nhaCungCapList;

            return View(sanPham);
        }

        // POST: CayCanh/Edit/{id}
        [HttpPost]
        public ActionResult Edit(string id, SanPham editedSanPham)
        {
            if (ModelState.IsValid)
            {
                SanPham sanPham = db.SanPham.FirstOrDefault(l => l.MaSanPham == id);

                if (sanPham == null)
                {
                    return HttpNotFound();
                }

                sanPham.MaSanPham = editedSanPham.MaSanPham;
                sanPham.TenSanPham = editedSanPham.TenSanPham;
                sanPham.GiaTien = editedSanPham.GiaTien;
                sanPham.MaNhaCungCap = editedSanPham.MaNhaCungCap;
                sanPham.SoLuong=editedSanPham.SoLuong;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(editedSanPham);
        }
        public ActionResult Delete(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            SanPham sanPham = db.SanPham.FirstOrDefault(l => l.MaSanPham == id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }

            return View(sanPham);
        }

        // POST: LoaiCay/Delete/{id}
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(String id)
        {
            QUANLYCAYCANHEntities db = new QUANLYCAYCANHEntities();
            SanPham sanPham = db.SanPham.FirstOrDefault(l => l.MaSanPham == id);

            if (sanPham == null)
            {
                return HttpNotFound();
            }

            db.SanPham.Remove(sanPham);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

caycanh/caycanh/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

caycanh/caycanh/Views/Home/Admin.cshtml
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="centered-box">
        <a href="@Url.Action("Index", "LoaiCay")">
            <h2>Loại Cây</h2>
        </a>
    </div>

    <div class="centered-box">
        <a href="@Url.Action("Index", "CayCanh")">
            <h2>Cây Cảnh</h2>
        </a>
    </div>

    <div class="centered-box">
        <a href="@Url.Action("Index", "NhaCungCap")">
            <h2>Nhà Cung Cấp</h2>
        </a>
    </div>
</div>
<div class="row">
    <div class="centered-box">
        <a href="@Url.Action("Index", "SanPham")">
            <h2>Sản Phẩm</h2>
        </a>
    </div>

    <div class="centered-box">
        <a href="@Url.Action("Index", "NhanVien")">
            <h2>Nhân Viên</h2>
        </a>
    </div>

    <div class="centered-box">
        <a href="@Url.Action("Index", "KhachHang")">
            <h2>Khách Hàng</h2>
        </a>
    </div>
    
</div>
<div class="row">
    <div class="centered-box">
        <a href="@Url.Action("Index", "DonHang")">
            <h2>Đơn Hàng</h2>
        </a>
    </div>

    <div class="centered-box">
        <a href="@Url.Action("Index", "ChiTietDonHang")">
            <h2>Chi Tiết Đơn Hàng</h2>
        </a>
    </div>

    

</div>
<!-- Các hàng khác tại đây -->

<style>
    .centered-box {
        border: 1px solid #ccc;
        padding: 10px;
        margin-bottom: 10px;
        width: 200px;
        height: 200px;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .row {
        display: flex;
        justify-content: center;
    }

    h2 {
        margin: 0;
        font-size: 18px;
    }

    a {
        text-decoration: none;
        color: #333;
    }
</style>

caycanh/caycanh/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

caycanh/caycanh/Views/Home/Index.cshtml
<main>
    <section class="image-slider">
        <div class="slider-container">
            <img src="~/img/2.jpg" alt="Image 1">
        </div>
    </section>

    <section class="intro-section">
        <div class="intro-container">
            <h2 class="intro-title">Chào mừng đến với chúng tôi</h2>

            <p class="intro-description">Chúng tôi cam kết mang đến cho bạn những sản phẩm chất lượng cao, đa dạng về kiểu dáng và kích thước, phù hợp với mọi không gian sống.</p>
            <p class="intro-description">Quý khách liên tục được cập nhật các sản phẩm mới nhất hãy liên tục cập nhật tại đây để có những thiết kế mới lại, độc đáo. Chúng sẽ giúp không gian của quý khách trở lên tuyệt vời,ngăn nắp và tươi xanh, nhiều tài nhiều lộc.</p>
        </div>
    </section>

    <section class="row" aria-labelledby="infoSectionTitle">
        <div class="product-container">
            <div class="product-item">
                <img src="~/img/sen-da-nau.jpg" alt="Product Image 1" style="width:63%;">
                <p class="image-description">Cây sen đá nâu</p>
            </div>
            <div class="product-item">
                <img src="~/img/davang.jpg" alt="Product Image 2" style="width: 95%;">
                <p class="image-description">Cây sen đá vàng</p>
            </div>
            <div class="product-item">
                <img src="~/img/sen-da-hong.jpg" alt="Product Image 3">
                <p class="image-description">Cây sen đá hồng</p>
            </div>
        </div>
    </section>
    <section class="row" aria-labelledby="infoSectionTitle">
        <div class="product-container">
            <div class="product-item">
                <img src="~/img/cuoc.jpg" alt="Product Image 1" style="width:54%;">
                <p class="image-description">Cuốc, xẻng</p>
            </div>
            <div class="product-item">
                <img src="~/img/phan.jpg" alt="Product Image 2" style="width: 95%;">
                <p class="image-description">Phân Bón</p>
            </div>
            <div class="product-item">
                <img src="~/img/tieu-canh-sen-da-9.jpg" alt="Product Image 3" style="width:54%;">
                <p class="image-description">Chậu kiểu</p>
            </div>
        </div>
    </section>
</main>

<style>
    .product-container {
        display: flex;
        justify-content: space-between;
    }

    .product-item {
        flex-basis: calc(33.33% - 10px);
        text-align: center;
    }

        .product-item img {
            max-width: 100%;
            height: auto;
        }

    .image-slider {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
        text-align: center;
    }

    .slider-container img {
        max-width: 100%;
        height: auto;
    }

    .intro-section {
        text-align: center;
        padding: 50px 0;
    }

    .intro-container {
        max-width: 600px;
        margin: 0 auto;
    }

    .intro-title {
        font-size: 24px;
        margin-bottom: 20px;
    }

    .intro-description {
        font-size: 16px;
    }
</style>